// react-backup/src/components/GUI/GUIMode.tsx
import React, { useState } from 'react';
import Navbar from './Navbar';
import Home from './sections/Home';
import Skills from './sections/Skills';
import Projects from './sections/Projects';
import Experience from './sections/Experience';
import Contact from './sections/Contact';

interface GUIModeProps {
  onSwitchMode: () => void;
}

const GUIMode: React.FC<GUIModeProps> = ({ onSwitchMode }) => {
  const [currentSection, setCurrentSection] = useState('Home');

  const renderSection = () => {
    switch (currentSection) {
      case 'Home':
        return <Home onNavigate={setCurrentSection} />;
      case 'Skills':
        return <Skills />;
      case 'Projects':
        return <Projects />;
      case 'Experience':
        return <Experience />;
      case 'Contact':
        return <Contact />;
      default:
        return <Home onNavigate={setCurrentSection} />;
    }
  };

  return (
    <div className="min-h-screen bg-slate-900 text-slate-200 font-sans">
      <Navbar 
        currentSection={currentSection} 
        onSectionChange={setCurrentSection} 
        onSwitchMode={onSwitchMode} 
      />
      
      <main className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
        {renderSection()}
      </main>

      {/* Optional minimal footer */}
      <footer className="py-6 text-center text-slate-500 text-sm border-t border-slate-800/50 mt-auto">
        <p>&copy; {new Date().getFullYear()} Aasim Syed. Built with React & Tailwind CSS.</p>
      </footer>
    </div>
  );
};

export default GUIMode;

// src/app/features/gui/gui-mode/gui-mode.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NavbarComponent } from '../navbar/navbar.component';
import { HomeComponent } from '../sections/home/home.component';
import { SkillsComponent } from '../sections/skills/skills.component';
import { ProjectsComponent } from '../sections/projects/projects.component';
import { ExperienceComponent } from '../sections/experience/experience.component';
import { ContactComponent } from '../sections/contact/contact.component';

@Component({
  selector: 'app-gui-mode',
  standalone: true,
  imports: [
    CommonModule, 
    NavbarComponent, 
    HomeComponent, 
    SkillsComponent, 
    ProjectsComponent, 
    ExperienceComponent, 
    ContactComponent
  ],
  templateUrl: './gui-mode.component.html'
})
export class GuiModeComponent {
  @Output() switchMode = new EventEmitter<void>();
  
  currentSection = 'Home';

  onSectionChange(section: string): void {
    this.currentSection = section;
  }

  onSwitchMode(): void {
    this.switchMode.emit();
  }

  get currentYear(): number {
    return new Date().getFullYear();
  }
}

<div class="min-h-screen bg-slate-900 text-slate-200 font-sans">
  <app-navbar 
    [currentSection]="currentSection" 
    (sectionChange)="onSectionChange($event)" 
    (switchMode)="onSwitchMode()"
  ></app-navbar>
  
  <main class="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8 md:py-12">
    @switch (currentSection) {
      @case ('Home') {
        <app-home (navigate)="onSectionChange($event)"></app-home>
      }
      @case ('Skills') {
        <app-skills></app-skills>
      }
      @case ('Projects') {
        <app-projects></app-projects>
      }
      @case ('Experience') {
        <app-experience></app-experience>
      }
      @case ('Contact') {
        <app-contact></app-contact>
      }
      @default {
        <app-home (navigate)="onSectionChange($event)"></app-home>
      }
    }
  </main>

  <footer class="py-6 text-center text-slate-500 text-sm border-t border-slate-800/50 mt-auto">
    <p>&copy; {{ currentYear }} Aasim Syed. Built with Angular & Tailwind CSS.</p>
  </footer>
</div>
