// src/app/features/gui/sections/contact/contact.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LucideAngularModule, Mail, Github, Linkedin, MapPin, Send } from 'lucide-angular';
import { PROFILE } from '../../../../core/data/content';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, LucideAngularModule],
  templateUrl: './contact.component.html'
})
export class ContactComponent {
  profile = PROFILE;

  readonly MailIcon = Mail;
  readonly GithubIcon = Github;
  readonly LinkedinIcon = Linkedin;
  readonly MapPinIcon = MapPin;
  readonly SendIcon = Send;
}

<div class="animate-in fade-in slide-in-from-bottom-4 duration-500">
  <div class="max-w-3xl mx-auto text-center space-y-12">
    <div class="space-y-4">
      <h2 class="text-4xl md:text-5xl font-extrabold text-white tracking-tight">Let's Connect</h2>
      <p class="text-lg text-slate-400 max-w-xl mx-auto">
        I'm currently open to new opportunities. Whether you have a question, a project proposal, or just want to say hi, I'll try my best to get back to you!
      </p>
    </div>

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-left">
      <a [href]="'mailto:' + profile.email" 
         class="group flex items-center gap-4 p-6 bg-slate-800/50 rounded-2xl border border-slate-700/50 hover:bg-slate-800 hover:border-sky-500/50 transition-all duration-300">
        <div class="p-3 bg-sky-500/10 rounded-xl text-sky-400 group-hover:scale-110 transition-transform">
          <lucide-icon [img]="MailIcon" class="w-6 h-6"></lucide-icon>
        </div>
        <div>
          <p class="text-sm text-slate-400">Email</p>
          <p class="text-slate-200 font-medium">{{ profile.email }}</p>
        </div>
      </a>

      <div class="flex items-center gap-4 p-6 bg-slate-800/50 rounded-2xl border border-slate-700/50">
        <div class="p-3 bg-slate-700/50 rounded-xl text-slate-400">
          <lucide-icon [img]="MapPinIcon" class="w-6 h-6"></lucide-icon>
        </div>
        <div>
          <p class="text-sm text-slate-400">Location</p>
          <p class="text-slate-200 font-medium">{{ profile.location }}</p>
        </div>
      </div>
    </div>

    <div class="flex flex-col sm:flex-row items-center justify-center gap-6 pt-8 border-t border-slate-800/50">
      <a [href]="profile.github" target="_blank" rel="noopener noreferrer" 
         class="flex items-center gap-2 text-slate-400 hover:text-white transition-colors">
        <lucide-icon [img]="GithubIcon" class="w-5 h-5"></lucide-icon>
        <span class="font-medium">GitHub</span>
      </a>
      <a [href]="profile.linkedin" target="_blank" rel="noopener noreferrer" 
         class="flex items-center gap-2 text-slate-400 hover:text-sky-400 transition-colors">
        <lucide-icon [img]="LinkedinIcon" class="w-5 h-5"></lucide-icon>
        <span class="font-medium">LinkedIn</span>
      </a>
    </div>

    <div class="pt-8">
      <a [href]="'mailto:' + profile.email"
         class="inline-flex items-center gap-2 bg-white text-slate-900 px-8 py-4 rounded-xl font-bold hover:bg-sky-50 transition-colors shadow-lg hover:shadow-sky-500/20">
        <lucide-icon [img]="SendIcon" class="w-5 h-5"></lucide-icon>
        Say Hello
      </a>
    </div>
  </div>
</div>

// react-backup/src/components/GUI/sections/Contact.tsx
import React from 'react';
import { Mail, Send } from 'lucide-react';
import { FaGithub, FaLinkedin } from 'react-icons/fa';
import { PROFILE } from '../../../data/content';

const Contact: React.FC = () => {
  return (
    <div className="py-8 animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-2xl mx-auto text-center">
      <div className="mb-12">
        <h2 className="text-3xl font-bold text-white mb-4">Get In Touch</h2>
        <p className="text-slate-400 text-lg">
          I'm currently looking for new opportunities. Whether you have a question or just want to say hi, I'll try my best to get back to you!
        </p>
      </div>

      <div className="flex flex-col sm:flex-row justify-center gap-6 mb-12">
        <a 
          href={`mailto:${PROFILE.email}`}
          className="flex items-center justify-center gap-2 px-6 py-4 bg-sky-500 hover:bg-sky-400 text-slate-900 rounded-lg font-semibold transition-colors"
        >
          <Mail className="w-5 h-5" />
          Say Hello
        </a>
      </div>

      <div className="bg-slate-800/30 border border-slate-700/50 rounded-xl p-8 max-w-md mx-auto">
        <h3 className="text-xl font-medium text-white mb-6">Connect Online</h3>
        <div className="flex flex-col gap-4">
          <a 
            href={`mailto:${PROFILE.email}`}
            className="flex items-center justify-between p-4 bg-slate-800/50 border border-slate-700 rounded-lg hover:border-sky-500/50 transition-colors group"
          >
            <div className="flex items-center gap-3 text-slate-300 group-hover:text-white transition-colors">
              <Mail className="w-5 h-5 text-slate-400 group-hover:text-sky-400" />
              <span>Email</span>
            </div>
            <ExternalIcon />
          </a>
          
          <a 
            href={PROFILE.github}
            target="_blank" rel="noopener noreferrer"
            className="flex items-center justify-between p-4 bg-slate-800/50 border border-slate-700 rounded-lg hover:border-sky-500/50 transition-colors group"
          >
            <div className="flex items-center gap-3 text-slate-300 group-hover:text-white transition-colors">
              <FaGithub className="w-5 h-5 text-slate-400 group-hover:text-sky-400" />
              <span>GitHub</span>
            </div>
            <ExternalIcon />
          </a>

          <a 
            href={PROFILE.linkedin}
            target="_blank" rel="noopener noreferrer"
            className="flex items-center justify-between p-4 bg-slate-800/50 border border-slate-700 rounded-lg hover:border-sky-500/50 transition-colors group"
          >
            <div className="flex items-center gap-3 text-slate-300 group-hover:text-white transition-colors">
              <FaLinkedin className="w-5 h-5 text-slate-400 group-hover:text-sky-400" />
              <span>LinkedIn</span>
            </div>
            <ExternalIcon />
          </a>
        </div>
      </div>
    </div>
  );
};

const ExternalIcon = () => (
  <Send className="w-4 h-4 text-slate-500 -rotate-45" />
);

export default Contact;
